// models/User.js

export default class User {
  /**
   * @param {Object} param0
   * @param {string} [param0.userId] - UUID, auto-generated by DB if not provided
   * @param {string} param0.fullName
   * @param {string} param0.email
   * @param {string} param0.passwordHash
   * @param {string} [param0.role] - defaults to 'user'
   * @param {string} [param0.phone]
   * @param {number} [param0.follow] - defaults to 0
   * @param {boolean} [param0.verified] - defaults to true
   * @param {string} [param0.image]
   * @param {bigint} [param0.balance]
   * @param {Date} [param0.createdAt]
   * @param {Date} [param0.updatedAt]
   */
  constructor({
    userId,
    full_name,
    email,
    password,
    role = "user",
    phone = null,
    follow = 0,
    verified = true,
    image = null,
    balance,
    createdAt = new Date(),
    updatedAt = new Date(),
  }) {
    this.userId = userId; // can be undefined when creating a new user
    this.full_name = full_name;
    this.email = email;
    this.passwordHash = password;
    this.role = role;
    this.phone = phone;
    this.follow = follow;
    this.verified = verified;
    this.image = image;
    this.balance = balance;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }
}
